### ISSUE TITLE
getProxyType() return DCH but isProxy() return 0... etcetera

### ISSUE THREAD

**Issue by ghost** [ip2location/ip2proxy-nodejs#2]
return value of isProxy() is not useful. First here is an IPA that has a proxy type of DCH, so isProxy should return 2 but it returns 0.
![](https://6s7a.qonq.gq)

it doesn't consider VPN proxy either, which I think it should (some PUBlic proxies i found were detected as VPN)
![](https://uz7t.qonq.gq)

there are probably more like this and it makes isProxy() not useful.

so instead I found this to work much better: `getProxyType(ip) == "-"`, because all the ip2proxy types I want to block.

**Comment by ip2location-com** [comment]
We have fixed the data. Please download the latest BIN file. However, do note that the LITE BIN only contains open proxies. If you wish to detect all types of proxies, you will need to subscribe to the commercial BIN.

https://lite.ip2location.com/ip2proxy-edition-comparison
