### ISSUE TITLE
Package broken on latest BIN file (2024.8.1)

### ISSUE THREAD

**Issue by devcube9** [ip2location/ip2proxy-nodejs#8]
With the latest BIN (2024.8.1), every field returns '-'

**Comment by ip2location-com** [comment]
What is the BIN filename that you're using?

**Comment by devcube9** [comment]
I've tried: 

- IP2PROXY-LITE-PX2 (IP-PROXYTYPE-COUNTRY)
- IP2PROXY-LITE-PX10 (IP-PROXYTYPE-COUNTRY-REGION-CITY-ISP-DOMAIN-USAGETYPE-ASN-LASTSEEN-THREAT-RESIDENTIAL)
- IP2PROXY-LITE-PX11 (IP-PROXYTYPE-COUNTRY-REGION-CITY-ISP-DOMAIN-USAGETYPE-ASN-LASTSEEN-THREAT-RESIDENTIAL-PROVIDER)

**Comment by ip2location-com** [comment]
Which IP address did you try?

**Comment by devcube9** [comment]
> Which IP address did you try?

None of the IP addresses I’ve tried so far worked (e.g., 8.8.8.8). Is there an IP that works on your end that I can test on my machine?

**Comment by ip2location-com** [comment]
You can try some of the IPs from [here](https://www.proxynova.com/proxy-server-list/).

Please note that the LITE PX BIN files only contains PUB (open proxy type).

**Comment by devcube9** [comment]
I see. The problem was the IP addresses I've tested. Thanks!
